id: ig-cpage-general-template
canonical: https://www.cpage.fr/ig/ig-cpage-general-template
name: IG Template CPage
status: draft
version: 0.1.0
date: 2025-12-30
title: Template IG CPage
publisher:
  name: CPage
  url: https://www.cpage.fr
contact:
  - name: CPage
    telecom:
      - system: email
        value: contact@cpage.fr
description: >-
  Template d'un IG FHIR CPage.
fhirVersion: 4.0.1
copyrightYear: 2026
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
  shownav: true

dependencies:

pages:
  index.md:
    title: Accueil

menu:
  "Accueil": index.html
